model_list:
  - model_name: {model_name}
    litellm_params:
      model: openai/model
      api_base: http://{service_name}:8000/v1
      api_key: "not-needed"

litellm_settings:
  drop_params: true
  set_verbose: true
