model_list:
  - model_name: Qwen3-1.7B
    litellm_params:
      model: openai/model
      api_base: http://vllm-llm-qwen3-1-7b:8000/v1
      api_key: "not-needed"
  drop_params: true
  set_verbose: true
