model_list:
  - model_name: Qwen3-1.7B
    litellm_params:
      model: openai/model
      api_base: http://172.25.208.100:8000/v1
      api_key: "not-needed"
  - model_name: glm-4-flash
    litellm_params:
      model: openai/glm-4-flash
      api_base: https://open.bigmodel.cn/api/paas/v4
      custom_llm_provider: openai
      api_key: "os.environ/GLM_4_FLASH_API_KEY"

litellm_settings:
  drop_params: true
  set_verbose: true
